// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clhpttamqyhmaaxccujb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsaHB0dGFtcXlobWFheGNjdWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODUwNjIsImV4cCI6MjA2NTU2MTA2Mn0.sf6NYVsIpOLvui6EEnjdrdU4a-6JMnR9zcYB2ZvG7dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);